services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./psql:/var/lib/postgresql/data
  prover:
    container_name: tdx-prover
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tdx-prover
    working_dir: /tdx-prover
    environment:
      PORT: "${PORT}"
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
