# Runtime stage
FROM public.ecr.aws/docker/library/nginx:1.25.2-alpine

# Run the application
# Copy the health.conf file to the nginx configuration directory
# Ensure nginx runs in the foreground

# Copy the health.conf file to the nginx configuration directory
COPY health.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
