[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.0.16", features = ["derive"] }
prover = { path = "../prover" }
rand = "0.8"
tokio = { version = "1.44.2", features = ["full"] }
hex = "0.4.3"
strum = "0.24.0"
strum_macros = "0.24.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
